export default {
  // 修改主题(颜色)
  THEME_CHANGE: 'THEME_CHANGE',
  // 主题初始化
  THEME_INIT: 'THEME_INIT',
  // 显示设置主题页面
  SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
  

  // 加载Popular 页面数据
  POPULAR_REFRESH: "POPULAR_REFRESH",
  // 加载Popular 页面数据 失败
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  // 加载Popular 页面数据 成功
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  // 加载Popular 更多成功
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  // 加载Popular 更多失败
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',


  // 加载Trending 页面数据
  TRENDING_REFRESH: "TRENDING_REFRESH",
  // 加载Trending 页面数据 失败
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  // 加载Trending 页面数据 成功
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  // 加载Trending 更多成功
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
  // 加载Trending 更多失败
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',

  // 刷新收藏状态
  FLUSH_POPULAR_FAVORITE: 'FLUSH_POPULAR_FAVORITE',
  FLUSH_TRENDING_FAVORITE: 'FLUSH_TRENDING_FAVORITE',

  // 收藏 加载数据
  FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA',
  // 收藏 加载数据成功
  FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',
  // 收藏 加载数据失败
  FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',

  // 语言加载成功
  LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',
};